name: Format, Lint, Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x 
      - name: Format
        run: deno fmt --check
      - name: Lint
        run: deno lint
      - name: Test
        run: deno test